import '../titles.dart';
import '../utils.dart';

Map<String, String> uz = {
  t.tel: "Telefon raqam",
  t.password: "Parol",
  t.addTeacher: "O'qituvchi qo'shish",
  t.teacher: "O'qituvchi",
  t.reception: "Qabul",
  t.group: "Guruh",
  t.students: "Tolib",
  t.students2: "ta o'quvchi",
  t.allBranches: "Barcha filiallar",
  t.lastName: "Familiya",
  t.firstName: "Ism",
  t.branch: "Filial",
  t.save: "Saqlash",
  t.back: "Ortga qaytish",
  myErrors.firstNameRequired:
      "Ismni kiritish majburiy va kamida 4 ta harfdan iborat bo'lishi kerak",
  myErrors.lastNameRequired:
      "Familiyani kiritish majburiy va kamida 4 ta harfdan iborat bo'lishi kerak",
  myErrors.telRequired: "Telefon raqamni kiritish majburiy",
  myErrors.branchRequired: "Filialni tanlash majburiy",
  t.stuff: "Xodim",
  t.info: "Info",
  t.support: "Yordamchi",
  t.pay: "To'lov",
  myErrors.selectFeature: "Kamida bitta imkoniyat berish majburiy",
  t.even: "Juft",
  t.odd: "Toq",
  t.groupName: "Guruh nomi",
  t.startTime: "Dars boshlanish vaqti",
  t.dayLesson: "Dars kuni",
  t.homework: "Uyga vazifa",
  t.newGroup: "Yangi guruh",
  t.firstLesson: "Birinchi dars",
  t.lastUnit: "Oxirgi bo'lim",
  t.selectUnit: "Bo'limni tanlash",
  t.selectTeacher: "O'qituvchini tanlash",
  t.address: "Manzil",
  t.name: "Nom",
  t.add: "Qo'shish",
  t.leaderboards: "Faollar",
  t.notPayed: "Tugagan",
  t.news: "Yangilar",
  myErrors.groupRequired: "Guruhni tanlash majburiy",
  t.selectGroup: "Guruhni tanlash",
  t.payed: "To'langan",
  t.comment: "Izoh",
  t.attendance: "Davomat",
  t.payments: "To'lovlar",
  t.groups2: "ta guruh",
  t.feature: "Imkoniyat",
  t.here: "Kelgan",
  t.notHere: "Kelmagan",
  t.haveReason: "Sababli",
  t.fullname: "I.F",
  t.status: "Holat",
  t.active: "Faollik",
  t.noLessons: "Hali darslar boshlanmagan",
  t.next: "Keyingisi",
  t.finish: "Tugatish",
  t.noStudent: "O'quvchi mavjud emas",
  t.themes: "Mavzular",
  t.unit2: "bo'lim",
  t.nameTheme: "Bo'lim nomi",
  t.cat: "Kategoriyalar",
  t.catName: "Kategoriya nomi",
  t.catDes: "Kategoriya haqida",
  myErrors.wrongPassword: "Parol xato",
  myErrors.wrongTel: "Telefon raqam xato!",
  t.fullname2: "To'liq ism sharif",
  t.nextLesson: "Keyingi bo'lim",
};
